# Generated by Django 2.1.1 on 2018-10-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=100)),
                ('retweet_count', models.IntegerField()),
                ('source', models.CharField(max_length=1000)),
                ('full_text', models.TextField()),
                ('url', models.CharField(max_length=1000)),
                ('user_mentions', models.TextField()),
                ('timestamp_ms', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tweets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('profile_image_url', models.CharField(max_length=1000)),
                ('profile_background_image_url', models.CharField(max_length=1000)),
                ('friends_count', models.IntegerField()),
                ('statuses_count', models.IntegerField()),
                ('description', models.TextField()),
                ('screen_name', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=500)),
                ('favourites_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('created_at', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tweets',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hacker_camp.UserProfile'),
        ),
    ]
