# Generated by Django 2.1.1 on 2018-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_camp', '0002_auto_20181009_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='full_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='lang',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='source',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user_mentions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_background_image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='screen_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
