# Generated by Django 2.1.1 on 2018-10-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_camp', '0003_auto_20181009_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
