# Generated by Django 2.1.1 on 2018-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_camp', '0004_auto_20181009_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='tweet_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
