# Generated by Django 2.1.1 on 2018-10-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_camp', '0005_tweets_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='hashtags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
