# Generated by Django 2.1.1 on 2018-10-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_camp', '0007_auto_20181009_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='url',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='user_mentions',
        ),
    ]
