# Generated by Django 2.1.1 on 2018-10-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_camp', '0008_auto_20181009_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='full_text',
            new_name='text',
        ),
    ]
